export const siteMetadata = {
  title: 'Elias Musleh | Las Vegas Full Stack, React & Node.js Developer',
  description: 'Las Vegas Full Stack Developer & Tech Consultant specializing in React, Next.js, Node.js, and IT services. Explore modern web projects, custom solutions, and expert tech consulting for Nevada businesses.',
  author: 'Elias Musleh',
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://eliasmusleh.com',
  locale: 'en-US',
  type: 'website',
  keywords: [
    'Elias Musleh',
    'Web Developer Las Vegas',
    'Full Stack Developer Nevada',
    'React Developer Las Vegas',
    'JavaScript Developer Las Vegas',
    'Frontend Developer Las Vegas',
    'Backend Developer Las Vegas',
    'Software Engineer Las Vegas',
    'Web Development Services Nevada',
    'Custom Web Applications Las Vegas',
    'React.js Developer',
    'Next.js Developer',
    'TypeScript Developer',
    'Node.js Developer',
    'MongoDB Developer',
    'Web Design Las Vegas',
    'Professional Web Developer',
    'Freelance Web Developer Las Vegas',
    'Tech Professional Las Vegas',
    'Website Development Nevada',
    'IT Services Las Vegas',
    'Tech Consulting Las Vegas',
    'IT Consulting Nevada',
    'Node.js Consulting',
    'Modern Web Projects',
    'Custom Solutions',
    'Projects',
    'Work'
  ],
  openGraph: {
    title: 'Elias Musleh | Las Vegas Full Stack, React & Node.js Developer',
    description: 'Las Vegas Full Stack Developer & Tech Consultant specializing in React, Next.js, Node.js, and IT services. Explore modern web projects, custom solutions, and expert tech consulting for Nevada businesses.',
    url: 'https://eliasmusleh.com',
    siteName: 'Elias Musleh Portfolio',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Elias Musleh | Las Vegas Full Stack, React & Node.js Developer',
    description: 'Las Vegas Full Stack Developer & Tech Consultant specializing in React, Next.js, Node.js, and IT services. Explore modern web projects, custom solutions, and expert tech consulting for Nevada businesses.',
  },
  verification: {
    google: 'your-google-verification-code', // You'll need to add this later
  }
}; 